# Site settings
title: YuhaoCheng's Homepage
description: YuhaoCheng's Homepage
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yuhao Cheng
user_description: Focs on AI/CV/IoT and other interesting things. I am applying the PhD and going to start in 2021.
user_title: Postgraduate
email: yuhao.cheng@outlook.com
github_username:  YuhaoCheng

# Google-analytics
google-analytics:
  id: ""
include: ['_pages']
exclude: ['package.json', 'src' , 'node_modules']
