# Site settings
title: YuhaoCheng's Homepage
description: YuhaoCheng's Homepage
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Yuhao Cheng
user_description: Focs on CV/DL/IoT and other interesting things. I am in the second year of my master's degree and going to apply for the Ph.D.
user_title: Postgraduate
email: yuhao.cheng@outlook.com
github_username:  YuhaoCheng

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
